artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shriadke/FetchSearch/raw/master/data/processed/synthetic_pair/synthetic_search_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "val"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/synthetic_search_data

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: msmarco-distilbert-base-v4
 
model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/
  model_path: msmarco-distilbert-base-v4 #artifacts/model_trainer/saved-search-model
  tokenizer_path: cross-encoder/ms-marco-MiniLM-L-6-v2
  metric_file_name: artifacts/model_evaluation/metrics.csv
  synthetic_df: data/processed/embeddings/msmacro_sent_embeddings.pkl